name: Publish Python distributions to PyPI and TestPyPI

on: push

jobs:
  build-n-publish:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Build source tarball
        working-directory: software
        run: python setup.py sdist

      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1.5
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          packages_dir: software/dist
          skip_existing: true

      - name: Publish distribution to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1.5
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: software/dist

